# Question 1

In [6]:
import numpy as np
import pdb

In [2]:
class divide: 
    def __init__(context, X, Y):
        context.X = X
        context.Y = Y
    def forward(context,X,Y):
        return(X/Y)
    def backward(context,X,Y):
        return(1/Y,X/Y**2)

In [3]:
A = np.array([[1, 4], 
              [-5, 8]])

In [4]:
B = np.array([[2, 4],
              [-3, 1]])

In [5]:
A/B

array([[0.5       , 1.        ],
       [1.66666667, 8.        ]])

In [6]:
exa = divide(A,B)

In [7]:
exa.forward(A,B)

array([[0.5       , 1.        ],
       [1.66666667, 8.        ]])

In [8]:
exa.backward(A,B)

(array([[ 0.5       ,  0.25      ],
        [-0.33333333,  1.        ]]),
 array([[ 0.25      ,  0.25      ],
        [-0.55555556,  8.        ]]))

# Question 2

### Scalar

In [9]:
class multiply:
    def __init__(context, X, a):
        context.X = X
        context.a = a
    def forward(context, X, a):
        Y = a*X
        return(Y)
    def backward(context, a): 
        dev_X = 1
        dev_Y = a*dev_X
        return(dev_Y)

In [10]:
a = np.array([[1,1],
             [-1,-1]])

In [15]:
exa = multiply(A,a)

In [16]:
exa.forward(A,a)

array([[ 1,  4],
       [ 5, -8]])

In [19]:
exa.backward(a)

array([[ 1,  1],
       [-1, -1]])

### Relu activation function

In [20]:
class relu:
    def __init__(context, X):
        context.X = X
    def forward(context, X):
        return(np.maximum(0,X))
    def backward(context,X):
        X[X<=0] = 0
        X[X>0] = 1
        return X

In [21]:
exa = relu(A)

In [22]:
exa.forward(A)

array([[1, 4],
       [0, 8]])

In [23]:
exa.backward(A)

array([[1, 1],
       [0, 1]])

### Softmax activation function

In [24]:
class softmax:
    def __init__(context, X):
        context.X = X
    def forward(context, X):
        expo = np.exp(X)
        expo_sum = np.sum(np.exp(X))
        soft = expo/expo_sum
        return soft
    def backward(context,X):
        expo = np.exp(X)
        expo_sum = np.sum(np.exp(X))
        soft = expo/expo_sum
        s = soft.reshape(-1,1)
        return np.diagflat(s) - np.dot(s, s.T)

In [25]:
exa = softmax(A)

In [26]:
A = np.array([1,2,3])

In [27]:
exa.forward(A)

array([0.09003057, 0.24472847, 0.66524096])

In [28]:
exa.backward(A)

array([[ 0.08192507, -0.02203304, -0.05989202],
       [-0.02203304,  0.18483645, -0.1628034 ],
       [-0.05989202, -0.1628034 ,  0.22269543]])

# Question 3

### Matrix multiplication

In [29]:
class Matrix_multiplication:
    def __init__(context,n,f):
        context.n = n
        context.f = f
    def forward(context,n,f):
        context.X = np.random.rand(n,f)
        context.W = np.random.rand(f,1)
        return(np.dot(context.X,context.W))
    def backward(context):
        return("grad_W:",context.X)

In [30]:
exa =Matrix_multiplication(3,3)

In [31]:
exa.forward(3,3)

array([[0.33521966],
       [0.82717004],
       [0.74666963]])

In [32]:
exa.backward()

('grad_W:',
 array([[0.04033222, 0.11582486, 0.79591893],
        [0.55958293, 0.89523051, 0.66590858],
        [0.38777749, 0.65178553, 0.93258716]]))

# Question 4

In [15]:
class broadcasting:
    def __init__(context,x):
        context.x = x
    def forward(context,x):
        Y = np.tile(x,16).reshape(16,len(x))
        context.Y = Y
        return(Y)
    def backward(context):
        return x*16

In [16]:
x=np.array([1,2,5])
exa = broadcasting(x)

In [17]:
exa.forward(x)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [18]:
exa.backward()

array([16, 32, 80])